### ISSUE TITLE
Initial grain creation fails on 0.51 - perhaps due to hyphen in Wave user name

### ISSUE THREAD

**Issue by Sing-Li** [jparyani/wave#3]
After successful app install, creating the first grain on a 0.51 server gives this error:

```
HTTP ERROR 500
Problem accessing /. Reason:
Failed to use Sandstorm username correctly
```

Debug log is:

```
 Sandstorm Debug log: Untitled Wave
... -   org.atmosphere.interceptor.PaddingAtmosphereInterceptor : Browser Padding Interceptor Support
4830 [main] INFO org.atmosphere.cpr.AtmosphereFramework -   org.atmosphere.interceptor.AndroidAtmosphereInterceptor : Android Interceptor Support
4833 [main] INFO org.atmosphere.cpr.AtmosphereFramework -   org.atmosphere.interceptor.HeartbeatInterceptor : Heartbeat Interceptor Support
4837 [main] INFO org.atmosphere.cpr.AtmosphereFramework -   org.atmosphere.interceptor.SSEAtmosphereInterceptor : SSE Interceptor Support
4841 [main] INFO org.atmosphere.cpr.AtmosphereFramework -   org.atmosphere.interceptor.JSONPAtmosphereInterceptor : JSONP Interceptor Support
4845 [main] INFO org.atmosphere.cpr.AtmosphereFramework -   org.atmosphere.interceptor.JavaScriptProtocol : Atmosphere JavaScript Protocol
4847 [main] INFO org.atmosphere.cpr.AtmosphereFramework -   org.atmosphere.interceptor.WebSocketMessageSuspendInterceptor : org.atmosphere.interceptor.WebSocketMessageSuspendInterceptor
4850 [main] INFO org.atmosphere.cpr.AtmosphereFramework -   org.atmosphere.interceptor.OnDisconnectInterceptor : Browser disconnection detection
4852 [main] INFO org.atmosphere.cpr.AtmosphereFramework -   org.atmosphere.interceptor.IdleResourceInterceptor : org.atmosphere.interceptor.IdleResourceInterceptor
4856 [main] INFO org.atmosphere.cpr.AtmosphereFramework - Set org.atmosphere.cpr.AtmosphereInterceptor.disableDefaults to disable them.
4861 [main] INFO org.atmosphere.cpr.AtmosphereFramework - Using EndpointMapper class org.atmosphere.util.DefaultEndpointMapper
4861 [main] INFO org.atmosphere.cpr.AtmosphereFramework - Using BroadcasterCache: org.atmosphere.cache.UUIDBroadcasterCache
4861 [main] INFO org.atmosphere.cpr.AtmosphereFramework - Default Broadcaster Class: org.atmosphere.cpr.DefaultBroadcaster
4861 [main] INFO org.atmosphere.cpr.AtmosphereFramework - Broadcaster Polling Wait Time 100
4861 [main] INFO org.atmosphere.cpr.AtmosphereFramework - Shared ExecutorService supported: true
4867 [main] INFO org.atmosphere.cpr.AtmosphereFramework - Messaging Thread Pool Size: Unlimited
4867 [main] INFO org.atmosphere.cpr.AtmosphereFramework - Async I/O Thread Pool Size: 200
4867 [main] INFO org.atmosphere.cpr.AtmosphereFramework - Using BroadcasterFactory: org.atmosphere.cpr.DefaultBroadcasterFactory
4867 [main] INFO org.atmosphere.cpr.AtmosphereFramework - Using WebSocketProcessor: org.atmosphere.websocket.DefaultWebSocketProcessor
4867 [main] INFO org.atmosphere.cpr.AtmosphereFramework - HttpSession supported: false
4867 [main] INFO org.atmosphere.cpr.AtmosphereFramework - Atmosphere is using Guice ObjectFactory for dependency injection and object creation
4867 [main] INFO org.atmosphere.cpr.AtmosphereFramework - Atmosphere is using async support: org.atmosphere.container.Jetty9AsyncSupportWithWebSocket running under container: jetty/9.1.z-SNAPSHOT with WebSocket enabled.
4869 [main] INFO org.atmosphere.cpr.AtmosphereFramework - Atmosphere Framework 2.1.0 started.
4869 [main] INFO org.atmosphere.cpr.AtmosphereFramework - 

    For Atmosphere Framework Commercial Support, visit 
    http://www.async-io.org/ or send an email to support@async-io.org

4888 [main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.w.WebAppContext@6845ec99{/,[file:/war/],AVAILABLE}
4901 [main] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@1bc5a281{HTTP/1.1}{localhost:9898}
4902 [main] WARN org.eclipse.jetty.server.session - Problem restoring session passwdadmin-bot@sandstorm.account
java.io.EOFException
    at java.io.DataInputStream.readFully(DataInputStream.java:197)
    at java.io.DataInputStream.readUTF(DataInputStream.java:609)
    at java.io.DataInputStream.readUTF(DataInputStream.java:564)
    at org.eclipse.jetty.server.session.HashSessionManager.restoreSession(HashSessionManager.java:641)
    at org.eclipse.jetty.server.session.HashSessionManager.restoreSession(HashSessionManager.java:585)
    at org.eclipse.jetty.server.session.HashSessionManager.restoreSessions(HashSessionManager.java:569)
    at org.waveprotocol.box.server.rpc.ServerRpcProvider.restoreSessions(ServerRpcProvider.java:420)
    at org.waveprotocol.box.server.rpc.ServerRpcProvider.startWebSocketServer(ServerRpcProvider.java:405)
    at org.waveprotocol.box.server.ServerMain.run(ServerMain.java:202)
    at org.waveprotocol.box.server.ServerMain.main(ServerMain.java:148)
4904 [main] WARN org.eclipse.jetty.server.session - Problem restoring session welcome-bot@sandstorm.account
java.io.EOFException
    at java.io.DataInputStream.readFully(DataInputStream.java:197)
    at java.io.DataInputStream.readUTF(DataInputStream.java:609)
    at java.io.DataInputStream.readUTF(DataInputStream.java:564)
    at org.eclipse.jetty.server.session.HashSessionManager.restoreSession(HashSessionManager.java:641)
    at org.eclipse.jetty.server.session.HashSessionManager.restoreSession(HashSessionManager.java:585)
    at org.eclipse.jetty.server.session.HashSessionManager.restoreSessions(HashSessionManager.java:569)
    at org.waveprotocol.box.server.rpc.ServerRpcProvider.restoreSessions(ServerRpcProvider.java:420)
    at org.waveprotocol.box.server.rpc.ServerRpcProvider.startWebSocketServer(ServerRpcProvider.java:405)
    at org.waveprotocol.box.server.ServerMain.run(ServerMain.java:202)
    at org.waveprotocol.box.server.ServerMain.main(ServerMain.java:148)
4905 [main] WARN org.eclipse.jetty.server.session - Problem restoring session passwd-bot@sandstorm.account
java.io.EOFException
    at java.io.DataInputStream.readFully(DataInputStream.java:197)
    at java.io.DataInputStream.readUTF(DataInputStream.java:609)
    at java.io.DataInputStream.readUTF(DataInputStream.java:564)
    at org.eclipse.jetty.server.session.HashSessionManager.restoreSession(HashSessionManager.java:641)
    at org.eclipse.jetty.server.session.HashSessionManager.restoreSession(HashSessionManager.java:585)
    at org.eclipse.jetty.server.session.HashSessionManager.restoreSessions(HashSessionManager.java:569)
    at org.waveprotocol.box.server.rpc.ServerRpcProvider.restoreSessions(ServerRpcProvider.java:420)
    at org.waveprotocol.box.server.rpc.ServerRpcProvider.startWebSocketServer(ServerRpcProvider.java:405)
    at org.waveprotocol.box.server.ServerMain.run(ServerMain.java:202)
    at org.waveprotocol.box.server.ServerMain.main(ServerMain.java:148)
4906 [main] WARN org.eclipse.jetty.server.session - Problem restoring session registration-bot@sandstorm.account
java.io.EOFException
    at java.io.DataInputStream.readFully(DataInputStream.java:197)
    at java.io.DataInputStream.readUTF(DataInputStream.java:609)
    at java.io.DataInputStream.readUTF(DataInputStream.java:564)
    at org.eclipse.jetty.server.session.HashSessionManager.restoreSession(HashSessionManager.java:641)
    at org.eclipse.jetty.server.session.HashSessionManager.restoreSession(HashSessionManager.java:585)
    at org.eclipse.jetty.server.session.HashSessionManager.restoreSessions(HashSessionManager.java:569)
    at org.waveprotocol.box.server.rpc.ServerRpcProvider.restoreSessions(ServerRpcProvider.java:420)
    at org.waveprotocol.box.server.rpc.ServerRpcProvider.startWebSocketServer(ServerRpcProvider.java:405)
    at org.waveprotocol.box.server.ServerMain.run(ServerMain.java:202)
    at org.waveprotocol.box.server.ServerMain.main(ServerMain.java:148)
4921 [main] WARN org.eclipse.jetty.server.session - Problem restoring session write.lock
java.io.EOFException
    at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:340)
    at java.io.DataInputStream.readUTF(DataInputStream.java:589)
    at java.io.DataInputStream.readUTF(DataInputStream.java:564)
    at org.eclipse.jetty.server.session.HashSessionManager.restoreSession(HashSessionManager.java:641)
    at org.eclipse.jetty.server.session.HashSessionManager.restoreSession(HashSessionManager.java:585)
    at org.eclipse.jetty.server.session.HashSessionManager.restoreSessions(HashSessionManager.java:569)
    at org.waveprotocol.box.server.rpc.ServerRpcProvider.restoreSessions(ServerRpcProvider.java:420)
    at org.waveprotocol.box.server.rpc.ServerRpcProvider.startWebSocketServer(ServerRpcProvider.java:405)
    at org.waveprotocol.box.server.ServerMain.run(ServerMain.java:202)
    at org.waveprotocol.box.server.ServerMain.main(ServerMain.java:148)
```

My display name is "Sing-Li" with a hyphen.  This may be the problem.

However, I did try to add a profile name on GitHub without the hyphen, but still get the same error when attempting to create a new Wave grain.

**Comment by jparyani** [comment]
I have a potential fix. Can you try going to https://alpha.sandstorm.io/grain/NTtXPX2BBJpuuiFRYhu2Sp and logging in with your github account?

**Comment by Sing-Li** [comment]
Just tried it.

I have no problem adding new entries with your grain at:

https://alpha.sandstorm.io/grain/NTtXPX2BBJpuuiFRYhu2Sp

However, creating a new grain on the same sever has the same problem:

https://alpha.sandstorm.io/grain/DerzrK9ry4v6rKjpD3i45t

**Comment by jparyani** [comment]
I installed a custom version of the spk with a fix. If you'd like to install it yourself, I've uploaded it to https://docs.google.com/file/d/0BzLCOahiEfRWR0dBeFR0a1FXRnM/edit, and we'll update sandstorm.io/apps in the next few days as well.
